### ISSUE TITLE
Add alternative metrics support

### ISSUE THREAD

**Issue by dijitali** [nodeshift/opossum#247]
Hystrix appears to now be deprecated [as of 19th Nov](https://github.com/Netflix/Hystrix/commit/a7df971cbaddd8c5e976b3cc5f14013fe6ad00e6#diff-04c6e90faac2675aa89e2176d2eec7d8).

Are there any current plans to support alternative metrics functionality?  Personally a [Prometheus](https://github.com/prometheus/prometheus)-compatible integration would be ideal but perhaps a more agnostic solution would be more future-proof and adaptable.

**Node.js Version:**
N/A

**Operating System:**
N/A

**Steps to Produce Error:**
N/A

**Comment by lance** [comment]
@dijitali yes - we are considering adding prometheus support.
