### ISSUE TITLE
Memory leak. Inability to reset and/or gracefully destroy breakers.

### ISSUE THREAD

**Issue by mastermatt** [nodeshift/opossum#248]
**Node.js Version:** v10.13.0
**Operating System:** Darwin Kernel Version 17.7.0 and 4.9.125-linuxkit
**Steps to Produce Error:** Call `new circuitBreaker(...)` more than 100 times in a single proc will produce the following log:
```
(node:25619) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 101 unpipe listeners added. Use emitter.setMaxListeners() to increase limit
(node:25619) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 101 drain listeners added. Use emitter.setMaxListeners() to increase limit
(node:25619) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 101 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:25619) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 101 close listeners added. Use emitter.setMaxListeners() to increase limit
(node:25619) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 101 finish listeners added. Use emitter.setMaxListeners() to increase limit
```

This issue was alluded to in #181 and #245, and I understand that the expected usage of this lib is to implement a singleton pattern for one (or small number) of circuit breakers.

My issue is with testing apps or libs that use this lib. There currently doesn't seem to be a way to ensure that circuit breakers have a clean slate between each test. My current workaround is to remove the reference of the singleton breaker in my code, which has the effect of creating new breakers even though the old ones are still in memory and registered with the `hystrixStream Transform`.

I can think of a few different approaches to solve this and I don't think they are mutually exclusive. 
- Graceful shutdown of circuit breakers.
  Give the `CircuitBreaker` class a method that shuts itself off. The idea would be that any future calls to `fire` would fail and once any local refs to the instance were gone the GC could clear it. This would involve calling out to its `hystrixStats` and adding a method to the `HystrixStats` class that basically calls `_readableStream.unpipe(hystrixStream)`.
- Reset individual circuit breakers.
  Give the `CircuitBreaker` class a method that resets it back to a state that mimics a new instance. At a minimum, this would need to set the circuit to closed and update its `Status` instance with all new buckets for its window. Decisions would need to be made on whether this method would also empty the semaphore, enable a disabled circuit, and/or restart the warm up logic.

**Comment by lance** [comment]
Thanks for the thorough write up @mastermatt. Since this is now the 3rd time this problem has arisen, I think that it's really a bug that we need to address.

**Comment by lance** [comment]
@mastermatt I've added `circuit.shutdown()` but not implemented a `reset()` function. Please have a look and let me know if you think this addresses your concerns.
