### ISSUE TITLE
A way to ignore certain type of errors

### ISSUE THREAD

**Issue by RidgeA** [nodeshift/opossum#262]
Hello! 

I use the `request` module with the opossum to communicate between microservices.

In case if other microservice returns HTTP 4xx error, this is treated as an error and could lead to breaker opening. But in major cases, 4xx HTTP status is a valid and expected result.

So, I need somehow to tell opossum to ignore certain types of error and return them as is and don't treat them as an error.

Is it feasible?

**Comment by lance** [comment]
All `opossum` does is proxy calls to the function it is provided. You could write a function that wraps your `request` calls, checking for acceptable responses and return a resolved promise when success or a rejected promise when failure.

**Comment by RidgeA** [comment]
Yeah, I could do this.
But 4xx errors I want to pass through opossum and return this response as an error (the same as without opossum) but without changing internal circuit breaker's stats. The subsequent code expects to receive an error in this case.
Other errors (such as 5xx or network errors) should lead to breaker opening.

**Comment by ComputerWolf** [comment]
I agree that a 4xx error does not necessarily mean that the service is unhealthy and should be configurable to not count as a failure, but it still makes sense to pass the error through as expected.

**Comment by lance** [comment]
I really think this is in the domain of the client application and not something that `opossum` should be doing. It does not make sense to inspect the return value of all functions protected by a circuit breaker, determine if the function is a remote call receiving a 404 and then performing some special behavior. This is code that belongs in userland, not the module.

**Comment by ComputerWolf** [comment]
@lance, while agree that any logic should happen outside of the module, right now it is all or nothing. There is no way to conditionally decide if a response should trip the circuit breaker and I would argue that there are some cases where a response should bypass the breaker. In those cases it is up to the module to provide the functionality to do so.

**Comment by RidgeA** [comment]
I totally agree that `opossum` should not inspect the errors and make a decision on to count this as an error or not. The logic should belong to called code and depends on many factors and business logic.

Let's imagine the following example (pretty close to that I encountered with):

```
const request = require("request-promise-native")
const {StatusCodeError} = require("request-promise-native/errors")

//....

let result;

//....

try {
   result = await request(url);
   //....
} catch (e) {
   if (e instanceof StatusCodeError && e.statusCode === 404)  {
      // an expected outcome - just to return an empty collection
      result = [];
   } else {
      // could be any other 4xx error or any of 5xx errors or any network error
      // this in an unexpected case and the error should be re-thrown
      throw e;
   }
}
```

Now I've got a task to add a circuit breaker to the request. I change the code:

```
const request = require("request-promise-native");
const {StatusCodeError} = require("request-promise-native/errors");
const opossum = require("opossum");

cosnt safeRequest = opossum(request, {});
//....

let result;

//....

try {
   result = await safeRequest(url).fire();
   //....
} catch (e) {
   if (e instanceof StatusCodeError && e.statusCode === 404)  {
      // expected outcome - just to return an empty collection
      result = [];
   } else {
      // could be any other 4xx error or any 5xx error or any network error - this in an unexpected case and the error should be re-thrown
      throw e;
   }
}
```

In this case `StatusCodeError`, that will be thrown by the request that wrapped with opossum will cause incrementing statistics counters.
With the default options, this will cause breaker opening and next call won`t happen at all and will return `Breaker is open` error.

This behaviour could be mitigated by configuration - `volumeThreshold` option, but this is rather hiding an error than an actual solution.


To my opinion, this could be managed in such a way:

1. Add to the CircuitBreaker one more option, e.g. `errorHandler` that will be a function with signature, for instance, f(err): boolean
2. the function could be called in https://github.com/nodeshift/opossum/blob/b0d4488c33da3a8f44181fd825f9b0376f1bef81/lib/circuit.js#L543 function
3. if `errorHandler` return true - the statistics shouldn't be incremented and this error shouldn't lead to opening the breaker if the `errorHandler` return false - the error is treated as unexpected and should lead to breaker opening.

With the changes, described above, the code would be look like:

```
const request = require("request-promise-native");
const {StatusCodeError} = require("request-promise-native/errors");
const opossum = require("opossum");

cosnt safeRequest = opossum(request, {
  errorHandler: funciton (error) {
    return error instanceof StatusCodeError && error.statusCode === 404;
  }
});
//....

let result;

//....

try {
   result = await safeRequest(url).fire();
   //....
} catch (e) {
   if (e instanceof StatusCodeError && e.statusCode === 404)  {
      // expected outcome - just to return an empty collection
      result = [];
   } else {
      // could be any other 4xx error or any 5xx error or any network error - this in an unexpected case and the error should be re-thrown
      throw e;
   }
}
```


`errorHandler` - is just a name from the top of my head, I don't like the name, but nothing better don't come to my mind right now.

I already made similar changes and need to polish the code and naming. After that, I would be ready to introduce PR with the feature, if you would accept it.

`errorHandler` could be not a function - it could be an instance of some class if you prefer such an approach.

I not a Java-guy, but AFAIK Hystrix allows for user's code to bypass metrics by wrapping an exception by wrapping the error with https://netflix.github.io/Hystrix/javadoc/com/netflix/hystrix/exception/HystrixBadRequestException.html

**Comment by lance** [comment]
OK - I can see the value of this. I'll reopen and give it some thought.

**Comment by lance** [comment]
@RidgeA after more thought and reading your suggestion a bit more carefully, yes I would definitely accept this change. I would like to see tests and docs along with it as well, please. If you want to submit what you have now as as a work in progress PR, that's fine. As for naming, I don't like `errorHandler` too much either, but if docs are good it doesn't really matter.

**Comment by jahredhope** [comment]
I'm attempting to use `opossum` on a [Axios HTTP client](https://github.com/axios/axios) and the ability to only open the circuit on 5xx errors is pretty important.

Not sure I like `errorHandler` but I'm not sure I have a better name. Perhaps `incrementError` or something?

The signature that @RidgeA presented looks good: `(error: Error) => boolean`

```js
const httpClient = () => {
  const breaker = opossum(axiosClient, {
    // Return true if the error
    incrementError: error => error.statusCode <= 500 && error.statusCode <= 599 &
  });


  return (...params) => breaker.fire(...params);
}
```

- Has anyone started work on this @RidgeA or @lance ?
- If not, are you open to a PR?

**Comment by lance** [comment]
@jahredhope thanks for your offer of a PR. I had this on my todo list for tonight, and it was a pretty simple change. Please have a look at it. https://github.com/nodeshift/opossum/pull/281

**Comment by RidgeA** [comment]
This is exactly what I expecting. Looking forward to a landing of this PR.

I have only one doubt - wouldn't be better to accept as an `errorHandler` promise/async function as well?
Personally I don't nee this at the moment, but it could be useful in some cases?...
