### ISSUE TITLE
Move examples to another repository?

### ISSUE THREAD

**Issue by helio-frota** [nodeshift/opossum#275]
That can help to silence greenkeeper a bit and deal with vulnerabilities in a less urgent way.

**Comment by lholmquist** [comment]
I think we can just remove the examples sub directories from the greenkeeper.json file, and greenkeeper will ignore them..... I think :)

https://github.com/nodeshift/opossum/blob/master/greenkeeper.json

**Comment by helio-frota** [comment]
@lholmquist seems good :+1:
