### ISSUE TITLE
UnhandledPromiseRejectionWarning when using opossum

### ISSUE THREAD

**Issue by rvillane** [nodeshift/opossum#282]
This is more a request for usability advice than reporting a bug.

**Node.js Version:**. 10.8.0
**Opossum Version:**. 1.10.1

I'm using opossum to handle HTTP interaction with an external service, this service exposes a typical health check path that returns HTTP 200 when successful or something different in case of issues.

The problem I faced was that someone renamed the health check path, causing a 404 HTTP response code back, and this is causing this warning:

(node:20) **UnhandledPromiseRejectionWarning**: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:20) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Here is my function that calls the health check path

        const healthOptions = {
            method: 'GET',
            uri: process.env.RESTFUL_SERVICE_HEALTHCHECK_URL,
        };

        /**
         * validates if the restful interface is responding - circuit breaker is expecting a Promise back,
         * every reject counts as a failure that could open the circuit.
         */
        function callHealthCheck() {
            return new Promise((resolve, reject) => {
                request(healthOptions)
                     .then(payload => {
                         resolve(payload);
                     })
                     .catch(err => {
                         reject(err);
                     });
            });
        }

Here is the circuit breaker definition:

const circuitBreakerOptions = {
        timeout: 5000, // If our function takes longer than 5 seconds, trigger a failure
        errorThresholdPercentage: 5, // When 5% of requests fail, trip the circuit
        resetTimeout: 1000 * 60 * 5, // After 5 minutes, try again.
    };

    const breaker = circuitBreaker(callHealthCheck(), circuitBreakerOptions);
    breaker.on('open', () => logger.debug('Circuit is open'));
    breaker.on('halfOpen', () => logger.debug('Circuit is halfOpen'));
    breaker.on('close', () => logger.debug('Circuit is close'));

And here is the main logic that receives a message and publishes this message to an external system:

    function messageHandler(message) {
        // circuit breaker drives the POST logic
        breaker.fire()
          .then(() => {
              // executes after a successfull healthcheck
              postMessageToEventInterface(message);
          })
          .catch(() => {
              // executes after a failure - circuit can be open after the failure
              postMessageToEventInterface(message);
          });
    }

    function postMessageToEventInterface(message) {
        if (breaker.closed || breaker.halfOpen) {
            sendEventMessage(message)
                .then(parsedBody => {
                    // POST succeeded...
                }).catch(err => {
                    logger.debug(`Error posting event - ${JSON.stringify(err)}`);
                    // opens the circuit in case of failures
                    breaker.open();
                });
        } else {
            logger.debug('Event post not executed because circuit is open');
        }
    }

I thought the circuitBreaker function -- callHealthCheck() in this case, was supposed to return either a resolved or a rejected promise, the function has a catch statement, then I'm not clear why I'm getting this UnhandledPromiseRejectionWarning when the health check endpoint is not available (HTTP 404).

**Comment by lance** [comment]
@rvillane based on the code you have provided, it's not clear to me why this might be happening. One thing I noticed though...

```js
const breaker = circuitBreaker(callHealthCheck(), circuitBreakerOptions);
```
This may be a typo, but the first parameter here should be `callHealthCheck` the function, not the return value from `callHealthCheck()`.

Any chance you could provide a simple reproducible example?

**Comment by rvillane** [comment]
ahhh, that made the trick, passing the function and not the function result.  Thanks a lot.
