### ISSUE TITLE
circuit breaker weird behaviour for 2 API routes

### ISSUE THREAD

**Issue by aizulhussin** [nodeshift/opossum#321]
## Operating System:Windows 10 Pro

Hi,

My scenario is i have 2 API routes created using Retify and 1 circuit breaker. 1 API is simulated as always success and the second API is simulated to experience latency.
Issue is, API 1 is also impacted by circuit breaker open, where it should not.

## Steps to Produce Error:
1. Create 2 API routes using Restify, each pointing to another external API. In my case i mock using Mockoon server
2. Create 1 circuitbreaker
3. Mock 1 api as success and 1 api to have latency 30 secs
4. API1 will call success mock API and API2 will call latency api
5. Trigger call to API1. Gets success. circuit breaker closes
6. Trigger call to API2. circuit breaker opens
7. Trigger call to API1,the circuit breaker opens. By right it should not open and not impacted by API2's circuit breaker

**Comment by lance** [comment]
Hi @aizulhussin - do you think you could put together a simple code sample that illustrates this behavior. I think I am following your description, but am not 100% sure. If you could provide a test case showing the failure that would be extremely helpful for me. Thanks!

**Comment by aizulhussin** [comment]
Hi Lance,

Here's the code example. You just need to add restify. The rest are based from your example.
I use Mockoon server to mock the external APIs (/thanos and /gamora)

Creating 2 circuit breakers solves this problem, but is it the right approach?

```
var restify = require('restify');



function respond(req, res, next) {
  res.send('hello ' + req.params.name);
  next();
}


function sendResponse(req, res, next,messages,startTime) {
  
   console.log("ID:"+req.params.id)
   console.log('Circuit Open:'+JSON.stringify(circuit.opened))
   //console.log('Half Open:'+JSON.stringify(circuit.halfOpen))
   //console.log('Closed:'+JSON.stringify(circuit.closed))
  
  if(messages!==undefined){
    body = messages.body
    res.send(body);
  }else{
    let duration  = new Date() - startTime;
    res.send("Something wrong with backend service. Response time:"+duration+" ms");
  }

  next();
}

function sendError(req, res, next,err) {
  console.log(err)
  res.send('something wrong but we are looking into it');
  next();
}



function callServiceB(req,res,next){
  console.log("----------------------------------------------")
  console.log("call service b")
  var start = Date.now();
  return circuit.fire({
    endpoint: 'http://localhost:3000/thanos'
  })
  .then((messages) => sendResponse(req, res, next,messages,start))
  .catch((err)     => sendError(req, res, next,err))
}


function callServiceC(req,res,next){
  console.log("----------------------------------------------")
  console.log("call service c")
  var start = Date.now();
  return circuit.fire({
    endpoint: 'http://localhost:3000/gamora'
  })
  .then((messages) => sendResponse(req, res, next,messages,start))
  .catch((err)     => sendError(req, res, next,err))
}



const circuitBreaker = require('opossum');
const client = require('roi');

const options = {
  timeout: 1000, // If our function takes longer than 1 seconds, trigger a failure
  errorThresholdPercentage: 10, // When 10% of requests fail, trip the circuit
  maxFailures:3,
  resetTimeout: 10000 // After 30 seconds, try again.
};

const circuit = circuitBreaker(client.get,options);
const circuit2 = circuitBreaker(client.get,options);

circuit.fallback(() => {
  console.log("Service unavailable")
});

circuit.on('reject',()=>{
  console.log("Reject")
})

circuit.on('halfOpen',()=>{
  console.log("half open")
})

//circuit2
/*
circuit2.fallback(() => {
  console.log("circuit2 Service unavailable")
});

circuit2.on('reject',()=>{
  console.log("circuit2 Reject")
})

circuit2.on('halfOpen',()=>{
  console.log("circuit2 half open")
})
*/


var server = restify.createServer();
server.get('/service-a/:id',callServiceB);
server.get('/service-c/:id',callServiceC);

server.listen(8080, function() {
  console.log('%s listening at %s', server.name, server.url);
});
```

**Comment by lance** [comment]
@aizulhussin yes, you need to have a separate circuit for each function. So, in `callServiceC()` you should be using `circuit2`. I was concerned from your initial description that this is what you were doing. :) 

Think about it this way - the circuit monitors and controls the behavior of its enclosed function. If you want to measure how `client.get()` is behaving overall, just use a single circuit. But if you want to measure and control the behavior of `circuit.get()` for a given individual URL, you would want to create a circuit that encapsulates that. E.g.

```js
const circuit1 = circuitBreaker(_ => client.get('https://my.url.com/pathA'));
const circuit2 = circuitBreaker(_ => client.get('https://my.url.com/pathB'));
```

Using this approach, you are measuring and controlling the behavior for each URL. With your example above, the single circuit is measuring the overall behavior of `client.get()` without taking into consideration the endpoint parameter.

Make sense?

I should probably make this clearer in the docs.

**Comment by aizulhussin** [comment]
Hi @lance , that makes sense. Thanks for the explaination
