### ISSUE TITLE
Add deprecations warnings and failures to CI builds

### ISSUE THREAD

**Issue by lance** [nodeshift/opossum#322]
Node provides flags that allow for failing when deprecated functionality is used. There are also flags for printing out deprecation warnings on functionality that will soon be deprecated. Turning on these flags will help us catch issues early that may cause failures in the future.

**Comment by lholmquist** [comment]
Just adding a link to the latest deprecations doc, https://nodejs.org/api/deprecations.html#deprecations_deprecated_apis

This has more info on the `--pending-deprecation` and `--throw-deprecation` flags
