### ISSUE TITLE
Passing function parameters to events

### ISSUE THREAD

**Issue by mykevinjung** [nodeshift/opossum#324]
This is more of a question than an issue. I like to use the parameters that were passed in the action function and do something in the event.  For instance, let's say `x` and `y` are passed in `asyncFunctionThatCouldFail` function and I like to print out the `x` and `y` on timeout event.  How can I do that?

```
const circuitBreaker = require('opossum');

function asyncFunctionThatCouldFail (x, y) {
  return new Promise((resolve, reject) => {
    // Do something, maybe on the network or a disk
  });
}

const options = {
  timeout: 3000, // If our function takes longer than 3 seconds, trigger a failure
  errorThresholdPercentage: 50, // When 50% of requests fail, trip the circuit
  resetTimeout: 30000 // After 30 seconds, try again.
};
const breaker = circuitBreaker(asyncFunctionThatCouldFail, options);

breaker.fire(params);
circuit.on('timeout',
  () => console.log(`x equal ${x} and y equal ${y}`)); // the parameters of asyncFunctionThatCouldFail
```

**Comment by lholmquist** [comment]
It doesn't look like that is currently possible.   The timeout event is only emitted with the error and the latency value.

@lance what do you think about adding the original function arguments to the timeout event when it is emitted?

I can send a PR

**Comment by lance** [comment]
@lholmquist yes - that sounds good. I wonder if it should necessarily be limited to `timeout`. The `open` and `failure` events might benefit from this as well.

**Comment by lholmquist** [comment]
agreed,  i'll added them too, to see how it feels.

**Comment by mykevinjung** [comment]
Thanks for the response.  It would be great to help diagnose the issue if we can know the inputs especially for those events like timeout and failure.
