### ISSUE TITLE
API requests are sending after the circuit is open

### ISSUE THREAD

**Issue by Sumeshkumar** [nodeshift/opossum#333]
## Steps to Produce Error:

I am trying to implement opossum in NUXT.js application in browser. 

I have installed the npm and imported it in the component. 

Below is my code looks like.

1. about.js(contains a function to get the data from service using axios)
```
  export default class AboutUs {
    getData () {
        return axios.get('url')
    }
}
```

2. about.vue(component)
```
<script>
import AboutUs from 'about.js'
import CircuitBreaker from 'opossum'

export default {
    methods() {
       getAboutUsData () {
            const options = {
                timeout: 500,
                errorThresholdPercentage: 50,
                resetTimeout: 30000
            }
            const $AboutUs = new AboutUs()
            const breaker = CircuitBreaker($AboutUs.getData(), this.options)
            breaker.fire().catch((e) => console.error(e))
            breaker.fallback(() => 'Service is not available')
            breaker.on('timeout', () => console.log('The request is taking too long to respond'))
            breaker.on('open', () => console.log('Breaker status changed to open'))
            breaker.on('close', () => console.log('Breaker status changed to closed'))
            breaker.on('halfOpen', () => console.log('Breaker status changed to half open'))
            breaker.on('semaphore-locked', () => console.log('Breaker is at capacity and cannot execute the request')) 
       }
    },
    mounted() {
        this.getAboutUsData()
     }
}
</script>
```

I can see the circuit is open in console but every time the request is sending to server even the circuit is open.

**Comment by Sumeshkumar** [comment]
Also curious to know where exactly opossum store the availability of the services.

**Comment by lance** [comment]
@Sumeshkumar I see a couple of issues in the code you have posted that would explain this behavior.

* Because you are creating a circuit in `getAboutUsData()`, every time that function is called a new circuit gets created. Creation of a circuit should only happen once for a given endpoint.
* When you create the circuit  you need to pass it a function. In your example, you are passing it the return value of `$AboutUs.getData()`, which is not what you want to do. This is why the circuit is open - it's trying to execute the return value. And it's also why you see the request being sent even though the circuit is open. Because the circuit is not actually sending the request - you are doing that when you call `$AboutUs.getData()` in the circuit creation function.
* You are setting listeners and fallback values on the circuit every time it is called. These typically should only happen once, when the circuit is created. 

Please modify your code to look something more like the following, and let me know how that goes for you.

```js

import AboutUs from 'about.js'
import CircuitBreaker from 'opossum'

const options = {
  timeout: 500,
  errorThresholdPercentage: 50,
  resetTimeout: 30000
}
const $AboutUs = new AboutUs();

// Note that here we do not actually call getData()
// instead we just provide the function to CircuitBreaker
const breaker = CircuitBreaker($AboutUs.getData, this.options);
breaker.fallback(() => 'Service is not available');
breaker.on('timeout', () => console.log('The request is taking too long to respond'));
breaker.on('open', () => console.log('Breaker status changed to open'));
breaker.on('close', () => console.log('Breaker status changed to closed'));
breaker.on('halfOpen', () => console.log('Breaker status changed to half open'));
breaker.on('semaphore-locked', () => console.log('Breaker is at capacity and cannot execute the request'));

export default {
  methods() {
    getAboutUsData() {
      breaker.fire().catch((e) => console.error(e));
    }
  },
  mounted() {
    this.getAboutUsData()
  }
}
```

**Comment by Sumeshkumar** [comment]
@lance Thanks for the reply. I will change my code and test it again.

Also another thing to check is, when the user refresh the page is it going to reset all the values or opossum storing the health check values some where in browser storage like localStorage?

**Comment by lance** [comment]
@Sumeshkumar opossum is not using browser storage, so all metrics are in memory.  Refreshing browser will refresh metrics.

**Comment by Sumeshkumar** [comment]
@lance Is this is same pattern for all javascript circuit breaker libraries(browser) or is there any library which store these details on the browser?

The reason I am asking this question is lets say a API request is getting network error or internal service error. If I understand correctly as per opossum the circuit will open and its works as expected.

But let say the user is refreshing the page continuously, in this scenario the metrics gets reset as this is in memory and API request will go through. Please correct me if I am wrong.

**Comment by lance** [comment]
@Sumeshkumar I believe you are correct, and that's a good point that I had not considered with the browser implementation. If you are interested in this feature, perhaps close this issue and open a new one (referencing this conversation), and we can add it to our triage/backlog and explore it more in depth.
