### ISSUE TITLE
MaxListenersExceededWarning is warning or real error

### ISSUE THREAD

**Issue by mykevinjung** [nodeshift/opossum#335]
I see `MaxListenersExceededWarning` log in my application.  I wonder if `MaxListenersExceededWarning` is simply a warning or it can really cause some issue in the circuit breaker.  Initially I thought `MaxListenersExceededWarning` is simply a warning by its name, but while investigating live site issue, I came to think that the issue might be related to circuit breaker and might be related to circuit listeners not having enough max listener setting.

For example, If I create 40 circuit breakers but if I set 35 max listeners, then will it cause a real problem?  If yes, what kind of problem would it cause?

By the way, I had a look at the following issue and PR.
https://github.com/nodeshift/opossum/issues/248
https://github.com/nodeshift/opossum/pull/250

Also, currently `MaxListenersExceededWarning` message has the **current** max listener setting.  Is it possible to log the number of listeners needed or to log suggested new max listeners?

**Comment by lance** [comment]
@mykevinjung there are a couple of circumstances where you might see this error described in the README.md file here: https://github.com/nodeshift/opossum#troubleshooting

Please have a look at this and let me know if this could be what you are seeing.

**Comment by mykevinjung** [comment]
@lance yes I had a look at that and other documents too, but it isn't clear `MaxListenersExceededWarning` is simply a warning or it can cause a real problem.  Can you tell about this?

By the way, the troubleshooting section has old code, e.g. `circuit.stats.getHystrixStream()` while the section right above it has `circuitBreaker.hystrixStats.getHystrixStream` which seems to be the latest one.

**Comment by lance** [comment]
@mykevinjung this is really just a warning. Node.js does not do anything other than [emit the warning](https://github.com/nodejs/node/blob/master/lib/events.js#L253-L267) and move on. But be careful, because this really could indicate a leak. 

Oh, and thanks for the heads up about the documentation errors.

**Comment by mykevinjung** [comment]
Ok, thanks for the confirmation.  Closing the issue now.

**Comment by lance** [comment]
> I think `circuitBreaker.hystrixStats.getHystrixStream` nor `breaker.stats.getHystrixStream().setMaxListeners(100);` are no longer available.
> 
> Is it okay to use this `breaker.status.setMaxListeners(100);` instead?

@yukha-dw you could but you should not have to. This error typically means something is not configured correctly.
