### ISSUE TITLE
Reuse metrics for a circuit breaker with different options

### ISSUE THREAD

**Issue by marikaner** [nodeshift/opossum#337]
Hey,

I would like to use a circuit breaker with some default options, but allow users of my tools to set their own options, while not losing the collected metrics of the previous runs.
As far as I can see there is no options to do this at the moment. Do you have an idea for a legitimate workaround?
Or will this be possible at some point in time?

**Comment by lance** [comment]
@marikaner any chance you can be a little more explicit about what you are trying to do? Could you post some sample code showing the behavior you would like. It's not entirely clear to me.

**Comment by marikaner** [comment]
Hey @lance, 

sorry for the late response, this totally slipped my mind!

So actually my use case is, that I want to use opossum to ensure resilience while working in a multitenant mode. To simplify, imagine the following example:
Some application makes calls to a specific system. For resilience there is a circuit breaker that is created using a `url` and some `options`. Now for every call it is collecting metrics.

For whatever reason a user of the application wants to modify the options of the circuit breaker, but only for himself. I want this user to be able to make a call with those options, while using the original circuit breaker, but failing only according his own options.

I am pretty sure this is currently not possible, but I wonder if this could be possible in the future or accomplished with a workaround somehow.

**Comment by lance** [comment]
@marikaner hmm - that's an interesting use case. Off the top of my head, I can't think of a way to easily achieve this without some changes. After giving it a full 3 minutes of thought (lol), I have a couple of questions that might help lead to a solution.

* Is there a subset of options that you are concerned about modifying? It sounds as though your case is specifically about failure/timeout and the like. If that is the case, it may be possible to add something like `fireWithOptions(opts, args...)`.
* Would it be reasonable to clone a circuit breaker from the original, but with new options? In this case, it may be that using shared metrics for this cloned circuit is possible.

Either of these solutions would require some work and would likely result in a minor, if not major, version bump.

**Comment by marikaner** [comment]
Hey @lance, sorry for the (very) late response.

In our case we wanted to modify either `timeout`, `errorThresholdPercentage` and / or `resetTimeout`. The project I am working on is a lib, where we want to allow changing the options when using the lib to make requests.

When investigating how to achieve this, we actually discussed cloning / copying circuit breakers with different option and sharing metrics for those. I guess this is one of the less invasive options to approach this idea. In the end an API as your proposed `fireWithOptions` is exactly how I would imagine consuming it.
