### ISSUE TITLE
Store metrics for browser implementation

### ISSUE THREAD

**Issue by Sumeshkumar** [nodeshift/opossum#342]
Store metrics for browser implementation so that its does not get reset while refresh the browser.

Use case: 

When browser refresh the metrics are getting reset currently. Can think of something like localStorage to store these values so that it does not reset.

This issue has been created as per the discussion on https://github.com/nodeshift/opossum/issues/333.

**Comment by lance** [comment]
@Sumeshkumar thank you for submitting this issue. I have given it some thought and played around a bit locally, and I think this is actually best left to the user.  It should be simple enough to add something like this to user code. Here, for example, is a very simple implementation for session storage of circuit metrics using [`opossum-prometheus`](https://github.com/nodeshift/opossum-prometheus).

```js
const circuit = new CircuitBreaker(protectedFunc);
const metrics = new PrometheusMetrics(circuit);

circuit.status.on('snapshot', _ => {
  sessionStorage.setItem('metrics', prometheus.metrics);
});
```

I am going to go ahead and close this issue for now.
