### ISSUE TITLE
Missing Documentation: options.cache

### ISSUE THREAD

**Issue by jonbrooks** [nodeshift/opossum#351]
`options.cache` seems to be missing from https://nodeshift.dev/opossum/ (though it is included in the Typings for `CircuitBreakerOptions`.

## Node.js Version:
n/a
## Operating System:
n/a
## Steps to Produce Error:
Visit documentation on https://nodeshift.dev/opossum/

**Comment by lholmquist** [comment]
@jonbrooks so, just a note on those typings.  Those are maintained by the community as a best effort i think.  So it is possible that the option doesn't exist anymore or was renamed to something else.  I would have to check
