### ISSUE TITLE
IE 11 support / babel

### ISSUE THREAD

**Issue by dptoot** [nodeshift/opossum#371]
## Node.js Version:
10

## Operating System:
Windows

## Steps to Produce Error:
Use opossum in IE 11.

It looks as though the opossum library isn't running through babel transpilation.  This is causing our IE11 bundles to fail due to many non-supported ES6 features like template-literals and class syntax.

I would think the simple addition of adding a babel transpile, utilizing the babel-preset-env, to the build would suffice for enough support.

Thoughts?

**Comment by dptoot** [comment]
I am able to workaround this today by adding a custom webpack rule to include opossum using our babel-loader.  But I would say that this is usually up to the package to handle es5 support.

**Comment by tavogel** [comment]
This fails for us when using UglifyJS as well. You can see template literals being used in the minified code:
https://cdn.jsdelivr.net/npm/opossum@4.1.0/dist/opossum.min.js

```js
new Error(`Timed out after ${this.options.timeout}ms`)
```

**Comment by tavogel** [comment]
I have opened a PR that works with `babel-loader` and `core-js@3`. Even if you don't want to use the `core-js` polyfills, you can use `babel-loader` and `preset-env` without `useBuiltIns` to at strip the template literals, and other syntactic sugar.

**Comment by lance** [comment]
Fixed in https://github.com/nodeshift/opossum/pull/380
