### ISSUE TITLE
Circuit breaker gets stuck in halfOpen state when using errorFilter

### ISSUE THREAD

**Issue by jairelton** [nodeshift/opossum#388]
## Node.js Version:
10.15.0
## Operating System:
MacOS 10.15.1
## Steps to Produce Error:
I'm experiencing an issue when trying to use `errorFilter` where the circuit gets stuck in the `halfOpen` state.

If you have a circuit in the `halfOpen` state and the subsequent failure is filtered by the error filter, the circuit remains in the `halfOpen` state, with `pendingClose === false` and no pending requests. This way it'll never go back to `closed`.

Step by step:

- The circuit reaches the error threshold and calls `open()`
- After the reset timeout, the circuit breaker goes into `halfOpen` state and `PENDING_CLOSE = true`
- The subsequent request changes `PENDING_CLOSE` to `false`
- The request fails and calls `failure()`
- The errorFilter filters the error and the failure is ignored
- The circuit breaker is now in an inconsistent state

I just sent a PR with a possible solution for this issue where I ignore the errorFilter when in HALF_OPEN state.

**Comment by lholmquist** [comment]
closing.  fixed in #389   released as 4.2.2
