### ISSUE TITLE
Is there a plan making a decorator wrapper?

### ISSUE THREAD

**Issue by yuu2lee4** [nodeshift/opossum#413]
Like https://github.com/DavideCarvalho/hystrixjsDecorator.

**Comment by lholmquist** [comment]
This isn't something we have planned.  It could be an interesting feature.

I know decorators are still being worked on and figured out at TC39, so i'm a little worried that if we did something,  even with babel, that things might change.  Just as an FYI, re-writing this library in typescript is not an option.


I'd say if someone from the community has the time and wants to start adding this feature and send a PR.  Then we can start to have a discussion if it works for us or not.  Currently we don't have any dependecies in this library, and that is still the goal
