### ISSUE TITLE
Consider using JSDoc to generate TypeScript types

### ISSUE THREAD

**Issue by lance** [nodeshift/opossum#418]
The opossum TypeScript types are currently maintained by community contributors, which is great. However, this requires that these folks keep up with API changes and update the types accordingly. Based on my quick read of [this article](https://dev.to/open-wc/generating-typescript-definition-files-from-javascript-5bp2), it seems like it would be possible to maintain these in this repository, and have the types automatically generated with JSDoc. It might go a good ways towards ensuring that the types and the API don't get out of sync.

**Comment by lholmquist** [comment]
that could be interesting.  Just as long as we aren't changing code to accommodate how JSDoc works.

**Comment by lance** [comment]
Here is the impl I recently did for CE: https://github.com/cloudevents/sdk-javascript/pull/155
