### ISSUE TITLE
errorThresholdPercentage clarification

### ISSUE THREAD

**Issue by Hongbo-Miao** [nodeshift/opossum#481]
I try to understand how does `errorThresholdPercentage` work.

I only found this in the readme:
```
errorThresholdPercentage: 50, // When 50% of requests fail, trip the circuit
```

For test, I found

https://github.com/nodeshift/opossum/blob/196457fe1da4c32d2f36b7aee70b2b2a424ff984/test/test.js#L197-L222

However, I am still having issue understanding about the start and end counting time.

Just listed three cases. Please correct me if I am wrong. Thanks!

**Case 1**

1. HTTP call failed

The error percentage is 100%, it will open the circuit breaker.

**Case 2**

1. HTTP call succeed
1. HTTP call failed

Now the error percentage is 50%, it will open the circuit breaker.

**Case 3**

1. HTTP call succeed
1. HTTP call succeed
1.  HTTP call failed
1.  HTTP call failed

Now the error percentage is 50%, it will open the circuit breaker.

And for all these cases, the counting will reset and start counting again after the circuit breaker close.

Am I right? Thank you so much!

**Comment by helio-frota** [comment]
@Hongbo-Miao I would say it is more to control / regulate what will happen, whether the circuit will open or not, based on the error rate.

I created this demo that you can play around the values and see the results:
https://github.com/nodeshift-starters/opossum-playground/tree/master/client-server-error-rate

It is using an opossum branch with debug logs so you can see the values on terminal

**Comment by Hongbo-Miao** [comment]
Thank you sooo much @Hongbo-Miao . The demo is very helpful!
Just notice in the demo that every firing during the circuit breaker is open will decrease the error rate. Really nice design!
