### ISSUE TITLE
rollingCountBuckets doc typo or clarification is needed

### ISSUE THREAD

**Issue by pelepelin** [nodeshift/opossum#482]
> options.rollingCountBuckets Number Sets the number of buckets the rolling statistical window is divided into. So, if options.rollingCountTimeout is 10000, and options.rollingCountBuckets is 10, then the statistical window will be 1000 1 second snapshots in the statistical window. Default: 10

What is `1000 1 second snapshots`? I would think that the sentence should be `the statistical window will be divided into 10 1-second buckets`.

**Comment by pelepelin** [comment]
While on it
> options.allowWarmUp boolean determines whether to allow failures without opening the circuit during a brief warmup period (this is the rollingCountTimeout property). Default: false allow before enabling the circuit.

`allow before enabling the circuit` after `false` looks unintended

**Comment by helio-frota** [comment]
@pelepelin good catch thank you 👍

**Comment by pelepelin** [comment]
> then the statistical window will be 1000/1 second snapshots in the statistical window.

This is still unclear. What is 1000/1 and what is snapshot? Also, "statistical window" is used 2 times in the same sentence, does it make sense which I'm missing? Should it be read as just `then the statistical window will be 1000 ms (1 second).`

If I guess correctly, the example assumes that kept history interval of 10 seconds is divided into 10 intervals of 1 second length, where the last one collects current statistics, once 1 second passes the oldest is discarded and a new one is created. Is this a correct approximation of implementation details?
