### ISSUE TITLE
State change from half_open to closed does not stay

### ISSUE THREAD

**Issue by muej** [nodeshift/opossum#484]
Hi,

we faced an issue on high load, that the state switch from `HALF_OPEN` to `CLOSED` seems not to stay. I.e. a successful call on `HALF_OPEN` should switch breaker to `CLOSED`, but actually the next call is rejected with _Error: Breaker is open_. While debugging the breaker state looked somehow  weird. All the state checks gave `false` (closed, opened, halfOpen, pendingClose).

I've created a fork with two commits. First to add an additional check to _circuit halfOpen_ and another one, with an assumed fix. Since I'm not really familiar with the implementation details, don't take it like it is, but hopefully it helps to identify the issue. :-)

## Steps to Produce Error:
https://github.com/muej/opossum/commit/2d5e6467dad6bf6699e1c1714cdf220c1bf8ffe3

## Possible issue/fix
https://github.com/muej/opossum/commit/12a64e80af939c29288f3f8de0e9141d8e97a4dc

## Node.js Version:
v14.9.0

## Operating System:
Linux 5.9.1-arch1-1 #1 SMP PREEMPT Sat, 17 Oct 2020 13:30:37 +0000 x86_64 GNU/Linux

**Comment by helio-frota** [comment]
Hi @muej sorry the delay in response.

I created an [example](https://github.com/nodeshift-starters/opossum-playground/tree/master/half-open-monitor) to monitor what happens with half open and that seems working as expected.

Can you please take a look and see if it helps ?

**Comment by muej** [comment]
Hi @helio-frota, thx for your reply. Mhh, yeah, I cannot see the error after several runs. :thinking: Since I can reproduce it with our code, I hope I can spent some time today to provide an example, which hopefully reproduces the issue.

**Comment by muej** [comment]
Mhh, played around and tried to create an example, but actually unable to do it :man_shrugging: Seems like something withing the function used in the breaker is blocking or doing some other weird stuff in case of error :thinking: 

I will close this issue for now. Sorry for the noise. I may post an update if we can figure out the root cause...

**Comment by helio-frota** [comment]
@muej  Thank you for report this. That was not a noise I think that was a contribution by reporting a case so we end up with a new demo/example :+1:
