### ISSUE TITLE
Default value for action in constructor

### ISSUE THREAD

**Issue by JimFung** [nodeshift/opossum#514]
https://github.com/nodeshift/opossum/blob/208495798b25c1194d95157c7a02db6dbbf649a3/lib/circuit.js#L138

Pretty unlikely scenario but if `action` is undefined and no name is provided for options in the constructor, then its possible to hit the following error:
```
TypeError: Cannot read property 'name' of undefined
```

As for a proposed fix, I'm unsure what a reasonable fallback value would be for action or if another solution (i.e. the user must pass a valid value for action) would be appropriate, I defer to the maintainers' expertise.

**Comment by helio-frota** [comment]
@JimFung thanks for catching that. PR sent with a fix :+1:
