### ISSUE TITLE
About fallbacks

### ISSUE THREAD

**Issue by dayvsonsales** [nodeshift/opossum#521]
Hello, 

I'm using circuit breaker to hold calls to some third party APIs and I have a doubt about if it's possible to get the exception in fallback function, cause I'm using the axios library and every response that's not a status code 200 throws an exception and calls the fallback, so I would like to personalize the fallback function based on this status code. Is this possible?

**Comment by helio-frota** [comment]
@dayvsonsales hi, seems that for this case you can use `errorFilter` https://github.com/nodeshift-starters/opossum-playground/blob/master/error-filter/client.js#L9. Please let me know if that works for you :+1:

**Comment by dayvsonsales** [comment]
@helio-frota thanks for your answer. I tried to use ``errorFilter`` but even with him, the fallback function is still being called. I thought that with this filter when it returns ``true`` the fallback wouldn't be called. But it still being called, even being considered a success. See the breaker stats:

```javascript

{
  failures: 0,
  fallbacks: 2,
  successes: 2,
  rejects: 0,
  fires: 2,
  timeouts: 0,
  cacheHits: 0,
  cacheMisses: 0,
  semaphoreRejections: 0,
  percentiles: {
    '0': 698,
    '1': 2734,
    '0.25': 698,
    '0.5': 698,
    '0.75': 2734,
    '0.9': 2734,
    '0.95': 2734,
    '0.99': 2734,
    '0.995': 2734
  },
  latencyTimes: [ 698, 2734 ],
  latencyMean: 1716
}

```

**Comment by helio-frota** [comment]
>  I would like to personalize the fallback function based on this status code. Is this possible?

Yes, you can take a look on https://github.com/nodeshift-starters/opossum-playground/blob/master/debuglog/core/fallback-parameters/index.js#L12

As you can see you can get the parameters so you can handle it as you wish. 

Please let me know if that works for you :+1:

**Comment by dayvsonsales** [comment]
@helio-frota thank you. It solved my problem. I had just to use error as the last parameter.

```javascript

this.circuitRecommendByCity.fallback((cityName, err) => {
	return this.handleFallbackByCity(cityName, err);
});

```

I think it'd be great to have an example with this, cause I had to look at lib code to figure out that the last parameter is the error parameter.

**Comment by helio-frota** [comment]
@dayvsonsales feel free to send a PR to https://github.com/nodeshift-starters/opossum-playground/ :+1: 

Closing this since it was solved
