### ISSUE TITLE
Question/Proposal - Distributed Configuration + Config Center (web/cli)

### ISSUE THREAD

**Issue by banduk** [nodeshift/opossum#550]
I'm using opossum and I was guessing if there is already a way to keep muiltiple processes circuit-breakers in sync and if there is a cli/web interface to ease the control of it.

**The scenario:**
- I'm using opossum to implement circuit-breaker for some third-party integrations
- I'm running my app in a multiple processes architecture and want the circuit-breakers to be synced among all processes
- Most of the integrations I have are not well documented and I don't really know how to configure each circuit-breaker
- Of course it would be possible to test each api and iterate their circuit-breaker configuration but there will be more integrations and they are quite important for my system and I prefer to be allowed to open/close/enable/disable/warmUp/shutdown each one of the circuit-breakers in a simple manner

**What I thougth**
- Keep redis keys with each circuit breaker state
- A redis Pub/Sub to which each circuit-breaker would listen to update its internal state
- A cli or web interface that reads and show all circuit breaker states and allow some actions to be performed

**Questions**
- Does it make sense? What would be the cons of having something like it?
- Is there something like this already there?

**Comment by lholmquist** [comment]
I think this idea is pretty cool,  having a UI for configuring the breakers.  But i don't think it should really be part of opossum, since we are trying to keep things as simple as possible.  If you start writing something and find Opossum needs a couple extra things, let us know and we can probably accomodate.

Sorry for the late reply on this,  it got lost in my email backlog

**Comment by lance** [comment]
> I think this idea is pretty cool, having a UI for configuring the breakers. But i don't think it should really be part of opossum, since we are trying to keep things as simple as possible. If you start writing something and find Opossum needs a couple extra things, let us know and we can probably accomodate.

Closing this
