### ISSUE TITLE
Wrong type definition

### ISSUE THREAD

**Issue by GiantKouKou** [nodeshift/opossum#596]
Hi,

I noticed an issue in type definition

The attribute `timeout` of `CircuitBreaker.Options` is declared as `number | undefined`

But in the constructor of the circuit breaker, we can see that it also accept `false` as value:

https://github.com/nodeshift/opossum/blob/536b312b7cc9f00156c83b87dc268c0ab14e023b/lib/circuit.js#L133

It's also mentionned in doc here :

https://github.com/nodeshift/opossum/blob/536b312b7cc9f00156c83b87dc268c0ab14e023b/lib/circuit.js#L38

So this property has the wrong type in the library @types/opossum

**Comment by lholmquist** [comment]
Nice catch.

The types as you pointed out are not in this repo, but are created by the community in the @types repo.  They would need to be updated there.

**Comment by GiantKouKou** [comment]
I created an issue in types repository

https://github.com/DefinitelyTyped/DefinitelyTyped/issues/55319

**Comment by GiantKouKou** [comment]
PR has just been merged
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/55346

I think we can close this issue 👍

**Comment by lholmquist** [comment]
thanks @GiantKouKou
