### ISSUE TITLE
[BUG] 'shutdown' event is not able to be fired

### ISSUE THREAD

**Issue by leejh3224** [nodeshift/opossum#620]
## Node.js Version:
v16.11.1

## Operating System:
macOS Monterey (12.0.1)

## Steps to Produce Error:
It always fails.

```ts
/**
 * Shuts down this circuit breaker. All subsequent calls to the
 * circuit will fail, returning a rejected promise.
 * @returns {void}
 */
shutdown () {
  this.disable();
  this.removeAllListeners();
    
  // intentionally omitted

  /**
   * Emitted when the circuit breaker has been shut down.
   * @event CircuitBreaker#shutdown
   */
   this.emit('shutdown');
}
```

With current implementation of `shutdown`, `shutdown` event can never be fired since `shutdown` removes all listeners from the beginning.

`this.emit('shutdown')` must be called before `this.removeAllListeners()`.

**Comment by lholmquist** [comment]
nice catch.   it looks like we don't actually test for that case.  we just test that the `fire` method returns an error if the breaker is shutdown
