### ISSUE TITLE
Calling fire() with function as parameter fails

### ISSUE THREAD

**Issue by Pazdr0** [nodeshift/opossum#624]
Hi,

We are trying to integrate opossum into our project, but we encountered an issue while calling function from external API.
Project is written in Typescript. We try to wrap following function in CircuitBreaker:

`send(addr: Addr, options: Partial<SenderOptions>, status?: Callback<R>): Result<Type, R>;`

like this:

```
const circuitBreaker = new CircuitBreaker(api.tx[section][method](...params).send, options)
const tmp = await circuitBreaker.fire(addr, options, (result): void => { ... }
```

While calling fire() we pass anonymous function as third parameter and we get following error:

> ERROR: Error on Foo error: {"stack":"TypeError: attempted to use private field on non-instance
>     at _classPrivateFieldBase (/home/user/Projects/Foo/src/node_modules/@babel/runtime/helpers/classPrivateFieldLooseBase.js:3:11)
>     at Function.send (/home/user/Projects/Foo/src/node_modules/@api/submittable/createClass.cjs:289:96)
>     at /home/user/Projects/Foo/src/node_modules/opossum/lib/circuit.js:603:38
>     at new Promise (<anonymous>)
>     at CircuitBreaker.call (/home/user/Projects/Foo/src/node_modules/opossum/lib/circuit.js:579:12)
>     at CircuitBreaker.fire (/home/user/Projects/Foo/src/node_modules/opossum/lib/circuit.js:497:22)
>     at /home/user/Projects/Foo/src/node_modules/Bar.js:171:56
>     at Generator.next (<anonymous>)
>     at fulfilled (/home/user/Projects/Foo/src/node_modules/Bar.js:5:58)
>     at runMicrotasks (<anonymous>)","message":"attempted to use private field on non-instance"} {"module":"Bar","@timestamp":"2022-01-06T10:52:35.614Z","@version":"1"}
> 

Bar.js:171:56 is where we call circuitBreaker.fire()

When calling send directly with same parameters everything works as expected.
Do you know if we are doing something incorrectly or maybe it is a bug?

Node v14.18.2
PopOS 20.04

**Comment by lance** [comment]
Hi @Pazdr0 - I don't think the problem has to do with passing an function, anonymous or otherwise. Here, for example, is a working version of a circuit that accepts a function which accepts a function.

```js
// A function which takes a function and returns
// the result of calling the provided function
function proxy(f) {
  return f();
}

// A circuit breaker for the proxy function
const circuit = new CircuitBreaker(proxy);

// Fire the circuit (aka call the function)
// with a function that returns a string
// and log the result
circuit.fire(_ => "Hello, world!")
  .then(console.log);
```

I don't suspect TypeScript to be the problem either. Instead, I think your `this` is not what you expect it to be, or some other similar scoping issue. If you can pare your issue down into something reproducible locally, I'd be happy to dig further.

**Comment by Pazdr0** [comment]
Thank you for your answer @lance. Unfortunately I'm unable to share my example here due to company's policy.
I was trying to dig into it yesterday, but with no luck.

You mentioned `this` could be something else I expect it to be, but I'm creating this breaker inside a out function.
And I put a `send` function of external API into breaker and call fire after creation.

May it be an issue that I try to create it inside a function and not as class variable?

**Comment by lance** [comment]
I'm sorry, but without some way to reproduce the issue it's pretty difficult to figure much out here. You might try calling `circuit#call` directly. and set the `context` parameter to be the `this` for whatever function you are trying to use. The body of `circuit#fire()` just proxies to the `call()` function, passing the circuit itself as `this`.
https://github.com/nodeshift/opossum/blob/6d71bad7db7791b2da5f0b4fe7d67ac70425b654/lib/circuit.js#L498-L500

**Comment by Pazdr0** [comment]
Sure, I understand. Thank you for your help.
I'll try to fix this issue based on your suggestions.
