### ISSUE TITLE
`CircuitBreaker.call` is not included in typescript types

### ISSUE THREAD

**Issue by steevsachs** [nodeshift/opossum#643]
A `CircuitBreaker` currently supports a `call` method that allows a user to pass context.  This works as expected, however, the typescript types at https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/opossum do not define this method.

Is there a reason this is omitted from the typings (ie, it's not planned for long term support)?  Can anyone confirm that the `call` method is considered stable and safe for production?

Thanks in advance!

**Comment by lance** [comment]
Hi @steevsachs the `CircuitBreaker#call()` method is definitely considered stable and safe. The documentation for it is here https://nodeshift.dev/opossum/#circuitbreakercall. Unfortunately, it seems the type did not get propagated to the DefinitelyTyped repo.

**Comment by steevsachs** [comment]
Thank you for confirming! Would a PR to DefinitelyTyped be welcome?  I'd be happy to put one together.

**Comment by lance** [comment]
> Thank you for confirming! Would a PR to DefinitelyTyped be welcome? I'd be happy to put one together.

It would - thanks! I'll keep this issue open until that lands.
