### ISSUE TITLE
Question about memory usage of opossum per breaker

### ISSUE THREAD

**Issue by YulongW** [nodeshift/opossum#648]
Hi, I tried to use this package for a graphql service and wrapped the API calls with breakers, and found that this package increased the memory usage of the service (runs in k8s) significantly over time (from ~80M to ~300M within a day for 2 breakers for a load of ~2 requests per second.)

Initially, I thought maybe there was a memory leak somewhere, but after ruling it out by cutting a few lines each time, I found that what caused the memory to increase is when the break called the `fire` function, which got me thinking maybe it does need that much of memory for some reason. And because the memory usage went up over time, it feels to me that it keeps track of some stats within each breaker over time, which makes sense. But using hundreds of MB of memory, and the memory usage doesn't go down when I stopped the traffic is what doesn't make sense to me. I also tried to lower or turn off the options that could result in higher memory usage, here are my current options when creating a breaker - **timeout: false, rollingCountTimeout: 5000, rollingCountBuckets: 5, rollingPercentilesEnabled: false.**

![image](https://user-images.githubusercontent.com/2530297/163652347-6bb9b805-20da-4297-adec-4623ec3f5949.png)

So I am trying to get some help in understanding the memory usage of this package for each breaker so I can better estimate the resources I should request for my service. Any help would be very much appreciated, and please let me know if you need any additional information.

## Steps to Produce Error:
1. Create a breaker for endpoints in a graphql service - tested with 2 breakers only
2. Deploy the service and run a load test of ~2 RPS
3. Observe the memory usage over time

**Comment by lance** [comment]
Hi @YulongW thank you for the thorough description of your issue. I tried to simplify the problem by removing everything but opossum - no graphql or other concerns.

https://github.com/lance/opossum-memory-test

This is a simple project that creates a circuit which does nothing other than get the amount of memory used by the running process. I ran it for 12 hours, firing the circuit every half second. You can see the results of that run here.

https://github.com/lance/opossum-memory-test/blob/6bb49fbac4e40d843b03ee75985b412e6e8baf8f/nohup.out#L1-L7

Total memory utilization for the process at the end of the run is 45 MiB, with a growth in usage of 10 MiB over 12 hours. This is admittedly a very simplified test, and I do think the 10 MiB of growth should be investigated. But it's not really close to the numbers you are seeing. Is there some way you could provide something I can run to test what you are seeing? Or could you simplify the problem space by removing some of the external concerns like graphql?

**Comment by YulongW** [comment]
Hi @lance, thank you for looking into this and doing the memory test. I think your test is great, and the only thing I feel is different is the action. I feel that switch the action from logging memory usage with an actual fetch call (to an endpoints that respond in in about 1-3 seconds - yeah the APIs that I am calling are kind of slow...) would be equivalent to my code regardless of graphql. (And I think graphql server doesn't affect the memory usage based on the previous memory usage. The memory usage stay flat when not using the brerakers for the same traffic. And what it really does is to call the APIs, wrapped by the breaker, based on the graphql query.)

And if it is needed, I can setup a repo that should be same as the service that I am having issue with, but different schema and calling some fake API that returns in seconds. (I cannot share what the exact code look like since the code is hosted internally and I shouldn't share :) ) Once I have it setup I'll share it with you, but it might take a bit of time.

**Comment by YulongW** [comment]
Another fact I found today is that the memory usage won't increase much and will stay flat, if no exception is thrown within a breaker to trigger it to open.

**Comment by YulongW** [comment]
I am closing this now. And here is a related update, we are able to use this package successfully without memory leak, though the fix was unexpected. The change I did was to use decorator in typescript instead of wrapping the async function to make testing easier, but that fixed the memory issue... I am suspecting it is probably an issue with nodejs but it is hard to tell.

**Comment by nurgasemetey** [comment]
Hi @YulongW 
Could you share which decorator did you use? I also have memory leak
