### ISSUE TITLE
Circuit is not calling the function to test when in HALF_OPEN state

### ISSUE THREAD

**Issue by nbhat000** [nodeshift/opossum#658]
## Steps to Produce Error: Build a circuit breaker that fails to `OPEN`, then to `HALF_OPEN` state.

Hello,

I'm trying to use Opossum to build a Circuit Breaker for AWS Lambda (I'm storing circuit state in `.env` locally, which is how I'm accounting for the reset of the state in a serverless scenario). I'm not sure I can post the exact code since it's on a corporate machine and I'm posting from my personal laptop.

Here's the issue: my circuit works for successes, and successfully goes to the `OPEN` state when there are sufficient failures. However, when it's in the `HALF_OPEN` state, it doesn't seem to ever call the function that is passed to the circuit breaker. I have several console.log's in that function, so I know it's calling when the circuit is closed. But in the `HALF_OPEN` state, it emits the `HALF_OPEN` event, but none of the logs in that function are printing out. In addition, it just stays in `HALF_OPEN` and never goes to `CLOSED`. It will go back to `OPEN` if I hit it with another call, but it then goes back to `HALF_OPEN` and never exits.

Upon examining the Opossum code, I found that that the behavior I'm seeing seems to be consistent with the code.

In `_startTimer`:
```ts
function _startTimer (circuit) {
      return _ => {
        const timer = circuit[RESET_TIMEOUT] = setTimeout(() => {
          circuit[STATE] = HALF_OPEN;
          circuit[PENDING_CLOSE] = true;
          /**
           * Emitted after `options.resetTimeout` has elapsed, allowing for
           * a single attempt to call the service again. If that attempt is
           * successful, the circuit will be closed. Otherwise it remains open.
           *
           * @event CircuitBreaker#halfOpen
           * @type {Number} how long the circuit remained open
           */
          circuit.emit('halfOpen', circuit.options.resetTimeout); <----- this line emits
        }, circuit.options.resetTimeout);
        if (typeof timer.unref === 'function') {
          timer.unref();
        }
      };
```

The `halfOpen` event is emitted after the correct `resetTimeout` interval. However, there is nothing listening for this `halfOpen` event that is emitted, the way there are listeners for other events on [lines 214-224 of `circuit.js`](https://github.com/nodeshift/opossum/blob/main/lib/circuit.js#L214). And I do not see a `halfOpen` function that retries the function when the circuit is `halfOpen` - only [this getter function in `circuit.js`](https://github.com/nodeshift/opossum/blob/main/lib/circuit.js#L396). So it seems like what I'm seeing in the wild is consistent with the codebase: the `HALF_OPEN` event is just emitted, then nothing else happens. 

**Am I missing something here? Why might the circuit in `HALF_OPEN` not be calling the underlying breaker function?**

A bit more of my code:

In order to simulate a downstream API call failing, then going back to normal, I've implemented something like this:

```ts
function unreliableFunction () {
    let isReliable = false;

    if(numOfFunctionCalls > 10) { // this is incremented in an env variable
       isReliable = true;
    }

    if(isReliable === false) {
        console.log('unreliable function');
        if (Math.random() < 0.6) {
            console.log('success');
            return lastValueFrom(this.httpService.delete(apiUrl)); 
        } else {
            console.log('failed');
            return lastValueFrom(this.httpService.delete(apiUrl));  // sending in wrong auth header token to fail it
        }
    } else {
        console.log('reliable function');
        return lastValueFrom(this.httpService.delete(apiUrl)); 
    }
}
```

The breaker is essentially implemented the same way you have it in the example in the docs.

Since none of the console logs here get logged, and since it never actually goes back to `OPEN`, I don't think the function is being called.

**Comment by lance** [comment]
Hi @nbhat000 - I wrote a simple test to try and reproduce the error you are seeing.

```js
test('When half-open, a successful fire() closes the circuit', t => {
  t.plan(4);

  const state = {
    closed: false,
    halfOpen: true,
    pendingClose: true
  };

  let called = false;
  const breaker = new CircuitBreaker(_ => called = true, { state });
  t.ok(breaker.halfOpen, 'should be halfOpen');
  t.ok(breaker.pendingClose, 'should be pendingClose');

  breaker
    .fire(1) // fire the breaker and be sure it closes
    .then(() => {
      t.ok(called, 'function should be called')
      t.ok(breaker.closed,
        'should be closed after successful invocation');
      t.notOk(breaker.halfOpen,
        'should not be halfOpen after successful invocation');
      t.notOk(breaker.pendingClose,
        'should not be pending close after successful invocation');
    })
    .then(_ => breaker.shutdown())
    .then(t.end);
});
```
This test passes just fine. I wonder if it has something to do with the function state and loading it from a `.env` file. Without more info, it's not possible to reproduce this.

Regarding the `halfOpen` event and what you are seeing being consistent with the code, I can assure you that's not the case! When you call `breaker.fire()` when a circuit is `halfOpen` there are a number of checks done before the function is actually called. For example, is the circuit shut down; is caching enabled. It's possible that one of these checks is not passing. But for the general case, if the call to `breaker.fire()` is successful, the breaker is closed here:

https://github.com/nodeshift/opossum/blob/9a1cd809544000751108f38207fd5b67be2bf4db/lib/circuit.js#L253-L257

And of course we have tests for all of this. ;)

Have you tried adding a fallback function to see if that's called while the circuit is half-open?

**Comment by lance** [comment]
@lholmquist I think this can probably be closed. I have not been able to reproduce it and we have not heard anything back.
