### ISSUE TITLE
Timeout config open the circuit in one shot, ignoring warmUp and rollingCountDuration configurations

### ISSUE THREAD

**Issue by ValterBortoletto** [nodeshift/opossum#660]
## Steps to Produce Error:

Im configuring the circuitbreaker to open every error, includes timeout, but the type timeout error open the circuit in one shot, ignoring statistics and rollingCountDuration with warmUp = true

configs
![image](https://user-images.githubusercontent.com/95650923/176508960-73d71042-b019-4eff-8011-822debd6c43c.png)

test
2 timeouts and OPEN circuit in 8 seconds, rollingCountDuration is 5 minutes
![image](https://user-images.githubusercontent.com/95650923/176509202-a0f55aaa-9237-4144-b9fb-94dc5994e991.png)

**Comment by lance** [comment]
Hi @ValterBortoletto thanks for reporting an issue. Can you please provide an example that reproduces what you are trying to describe? I'm not sure I understand what exactly the issue is. Thanks.
