### ISSUE TITLE
Question about circuit breaker on multiple API calls

### ISSUE THREAD

**Issue by kevkcc** [nodeshift/opossum#668]
Hi,

Does Opossum support having a circuit breaker on multiple API calls? i.e. something like the below:
```
const breaker = new CircuitBreaker(maybeAnArrayOfAsyncFunctionsThatCouldFail, options);
```
This is roughly equivalent to the sub circuit feature available in Brakes:
https://www.npmjs.com/package/brakes#sub-circuits

If not, is there a recommended workaround for this? Thanks!

**Comment by lance** [comment]
@kevkcc thanks for reporting this. No, this pattern is not currently supported. If you feel up for it, contributions are welcome!

**Comment by lance** [comment]
@lholmquist I think this can probably be closed as well
