### ISSUE TITLE
Add AbortController support

### ISSUE THREAD

**Issue by raytung** [nodeshift/opossum#673]
Hey team,

This is a feature request to add support for `AbortController` 
- https://developer.mozilla.org/en-US/docs/Web/API/AbortController
- https://nodejs.org/docs/latest-v15.x/api/globals.html#globals_class_abortcontroller

With `AbortController`, Opossum should be able to send signal to the underlying method to abort the on going request. This is useful in conjunction with Opossum's timeout feature, where Opossum will fail the on going request but also allow the on going HTTP request to be properly aborted instead of hanging around in the background 

- https://nodejs.org/api/http.html#httprequestoptions-callback
- https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API#aborting_a_fetch

**Comment by lance** [comment]
Fixed in https://github.com/nodeshift/opossum/pull/674
