### ISSUE TITLE
Support for Distributed System

### ISSUE THREAD

**Issue by mayankagarwals** [nodeshift/opossum#675]
Hey, 

This is a request to understand the current distributed systems support from opossum. 
We can store the latest rolling window state in a common store, but does it make sense for opossum to provide it out of the box?

**Comment by gopiprasanthpotipireddy** [comment]
@mayankagarwals  I observed almost every top used circuit breaker module in other eco system also are reluctant to add this feature.

**Discussion Thread: 

**.NET** Polly**
https://github.com/App-vNext/Polly/issues/287#issue-247299690

**Java : resilience4j**
https://github.com/resilience4j/resilience4j/issues/419

**Comment by lance** [comment]
@gopiprasanthpotipireddy @mayankagarwals we do have the ability to store and reload a circuit's state. It is discussed in the README.md here https://github.com/nodeshift/opossum#breaker-state-initialization. We do not want to pull external dependencies into this module, so the integration with redis or other state stores is left up to the user.

**Comment by jdmarshall** [comment]
I think at some point we will discontinue circuit breakers in favor of putting rate limiting in front of more services, instead of just entrypoints. Having two classes of service for rate control gets very weird especially when services are called both by external and internal processes.

**Comment by lance** [comment]
@lholmquist I am going to close this as `wontfix` as there seem to be no plans to address it. Please feel free to reopen it if you think otherwise.
