### ISSUE TITLE
Is there any way to use circuit breaker with resolver functions of graphql server?

### ISSUE THREAD

**Issue by ArchitectAK** [nodeshift/opossum#706]
Is there any way to use circuit breaker with resolver functions of graphql server?

TO be exact, I wanna apply circuit breaker on method of class resolver in type-graphql server.

**Comment by pavellishin** [comment]
Howdy! I'm working on something very similar right now at work, trying to use opossum for this.

**Comment by ArchitectAK** [comment]
Hi,
I have solved the issue for me and have created PR to add example of how to use decorater for cirbuit brekaer and use it on graphql function (or any async function)
PR- https://github.com/nodeshift-starters/opossum-examples/pull/420

**Comment by pavellishin** [comment]
How does this work? Our classes which implement the actual GraphQL resolvers don't last for the lifetime of the server - they get spun up per-request. I don't see any changes in that PR that would actually keep a timer running.
