### ISSUE TITLE
Breaker State Initialization not working as documented

### ISSUE THREAD

**Issue by kaplanan** [nodeshift/opossum#735]
## Node.js Version:
v16.15.1

## Operating System:
MacOS 13.1

## Steps to Produce Error:
Just follow along the example in the[ documentation of Breaker State Initialization](https://www.npmjs.com/package/opossum). 

```
const state = breaker.toJSON(); // show open: true
const breaker = new CircuitBreaker({state: state});
console.log(breaker.opened) // returns false
```

Although I'm using [@types/opossum](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/opossum) this should not be the root of the issue, since when looking into the source code of opossum v7.1.0, there is no logic (neither in the constructor, nor anywhere else) which would make this work. Is the documentation deprecated?

**Comment by lance** [comment]
> If you don't mind, I will fix this with a PR and link this issue to it.

@kaplanan your contribution would be appreciated! Do you still plan to do this?

**Comment by lance** [comment]
@kaplanan just checking if you still intend to submit a PR for this. It would be welcomed.

**Comment by adamruggles-powerschool** [comment]
I'm not even seeing `const breaker = new CircuitBreaker({state: state});` as an option in typescript.

**Comment by lholmquist** [comment]
@adamruggles-powerschool the typescript bindings are supplied by https://github.com/DefinitelyTyped/DefinitelyTyped , which community members have been updating.  So most likely they could be out of date
