### ISSUE TITLE
How can I get single CB for whole HTTP Client with Opossum?

### ISSUE THREAD

**Issue by murbanowicz** [nodeshift/opossum#838]
Hi,
I really like this project and I appreciate your work on it.

I am missing one thing - how to use single breaker for a e.g. whole HTTP Client for given dependency.
Having separate on each method does make much sense in such scenario and having single CB for the single dependency like this makes much more sense.

Is there any way to get it working like that with Opossum?

**Comment by lholmquist** [comment]
do you have a small code(even pseduo code would work) example of what you are looking for?

**Comment by murbanowicz** [comment]
E.g.

```typescript
export class MyHttpClient {
  getOrders() {
     this.circuitBreaker....(???) // call get /orders on target service
  }
  
    getPayments() {
     this.circuitBreaker....(???) // call get /payments on target service
  }
}

both should use same CB as they are targeting the very same service.

**Comment by lholmquist** [comment]
If you are using a class, could you just setup the circuit breaker in the constructor and then `this.circuitBreaker` should reference that single instance?

**Comment by lholmquist** [comment]
closing since we didn't get a response from the previous suggestion
